### ISSUE TITLE
Hi,I achieved the other one like this with nodejs.

### ISSUE THREAD

**Issue by yeongjet** [SzymonKatra/AllDataSheetFinder#5]
This is a very useful tool, it help me a lot! but I have to complie it with vs2015. So, I override it with nodejs from your codes,thanks!  (Sorry, I haven't get your permission), now, you can see it in my github or see www.anizy.com. Maybe we can help more people. :)

**Comment by SzymonKatra** [comment]
Thanks. I'm happy that this tool is useful for you and inspired to create something like that in browser.

You analyzed code for searching and obtaing pdf and implemented in node.js, yes? Thanks that you inform me about that. I spent a lot of time to work out this. I think that some parts of my code are hard to read (especially this mechanism), but you got it :)

I would be grateful if you put a small banner on your site with link to AllDataSheetFinder site. I also can put a reference to Anizy in app, but i think that you should first refine site a little bit.

I tried to use it, but it seems that your site only returns datasheet of parts contains the text you typed. Try to find some elements using your site and my app, for example L293D, 1N4007 and comapre results. You will see what's wrong.

Tip: Look on **sField** GET parameter and **SearchOption** enum which is in the AllDataSheetSearchContext.cs file.

You can email me if you want. Address is on my site: http://szymonkatra.github.io/
