### ISSUE TITLE
Nazwa zdarzenia problemu: CLR20r3

### ISSUE THREAD

**Issue by 0o-WaSyL-o0** [SzymonKatra/AllDataSheetFinder#6]
Witam.
Zaraz po zakończeniu wyszukiwania danej noty katalogowej, dokładniej zaraz po wyświetleniu listy dostępnych not, program wywala z takim oto podpisem:
"Podpis problemu:
  Nazwa zdarzenia problemu: CLR20r3
  Podpis problemu: 01: AllDataSheetFinder.exe
  Podpis problemu: 02: 0.3.11.0
  Podpis problemu: 03: 57e40ea3
  Podpis problemu: 04: System
  Podpis problemu: 05: 4.7.3353.0
  Podpis problemu: 06: 5c1ab603
  Podpis problemu: 07: ebb
  Podpis problemu: 08: 47
  Podpis problemu: 09: System.NotSupportedException
  Wersja systemu operacyjnego: 6.1.7601.2.1.0.768.3
  Identyfikator ustawień regionalnych: 1045
  Dodatkowe informacje 1: 0a9e
  Dodatkowe informacje 2: 0a9e372d3b4ad19135b953a78882e789
  Dodatkowe informacje 3: 0a9e
  Dodatkowe informacje 4: 0a9e372d3b4ad19135b953a78882e789
"
Załączam zrzucik :)

![zrzucik](https://user-images.githubusercontent.com/50052282/56851439-a8dd1d80-690f-11e9-9a97-d73a864def77.JPG)

**Comment by SzymonKatra** [comment]
Problem naprawiony w wersji 0.3.12. Program powinien zaproponować automatyczną aktualizację po uruchomieniu.

Problem fixed in 0.3.12 version. The application should propose auto-update on startup.

https://github.com/SzymonKatra/AllDataSheetFinder/releases/tag/0.3.12
